services: mongodb
rvm:
  - 2.1.0
  - 1.9.3
  - 2.0.0
  - jruby
notifications:
  recipients:
    - jordon@envygeeks.com
branches:
  only:
    - master
env:
  - "MONGOID_VERSION=3.1.6"
  - "MONGOID_VERSION=4.0.0"
