test:
  sessions:
    default:
      database: mongoid-find_by-test
      hosts:
        - 127.0.0.1:27017
  options:
    use_activesupport_time_zone: true
    preload_models: false
    use_utc: true
    include_root_in_json: false
    raise_not_found_error: false
    scope_overwrite_exception: true
    include_type_for_serialization: true
